### PR TITLE
Added a lot more Baud Rate options and removed requestPort filter

### PR DESCRIPTION
**Pull request by stignarnia**

### CODE REVIEW

**Comment by geekuillaume** [comment]
Thanks for this update! Do you know why your yarn.lock file is different even if you didn't installed any new package?

**Comment by stignarnia** [comment]
I think it's yarn 1.x vs yarn 2.x or something like that. You can keep yours if you like, I don't think it would break anything

**Comment by geekuillaume** [comment]
You're right, I was using an old version of yarn. I updated it and included the changes in your PR. Merging now. Thanks for your work! :)

**Comment by stignarnia** [comment]
Thank you for this tool!

**Pull request merged**
