### PR TITLE
A PR with few bugfixes and few features

### PR DESCRIPTION
**Pull request by askuric**
This is a new PR with the same changes from #2 

main additions are:
- added torque control selector
- monitoring control per motor
  - serial + monitoring variables
- fixing the accordion up/down arrows on text entries (FocScalar)
- adding jogging feature for FocScaler 

NOTE: 
I've tried several strategies to not sue `document.getElementById` in the monitoring variable selector, but I had no luck. When I connect a variable with the Checkbox checked property then in the onchange handler this variable is not updated right away. What I mean is if one checkbox is checked the other checkboxes' handlers dont see the change right away. So if I click few of the checkboxes in a row, the state in the connected variables is completely off.
So I opted for a solution using the pure javascript. :D    
I am sure you can find a better solution for this and its probably my inexperience with the typescript that's causing it.

### CODE REVIEW

**Comment by geekuillaume** [comment]
I still don't have the permission to push to your repository. It's maybe because you're using your `main` branch for this PR. Can you create another branch and try again?

**Comment by askuric** [comment]
Huh, that's strange, you should be able to push to my fork now though.
image


>If checked, users with write access to `geekuillaume/simplefoc-webcontroller` can add new commits to your `main` branch. You can always change this setting later.

**Comment by geekuillaume** [comment]
I've tried again and it's still not working. Can you create another branch than `main` on your fork and use this branch for this PR?

**Comment by askuric** [comment]
Ok

**Pull request closed without merging**
